// Executes the exact pure math and CSV exporter defined in src/index.template.html.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../src/index.template.html',import.meta.url),'utf8');
const source=html.match(/^\s*\/\/ GD:MATH:BEGIN[^\n]*\n([\s\S]*?)^\s*\/\/ GD:MATH:END/m)?.[1];
assert.ok(source,'math boundary must exist in the source template');
const core=vm.runInNewContext(`${source}; ({linearAxis,mapImagePoint,orderedValues,csvBytes})`,{Blob});
const near=(got,want,tolerance=1e-9)=> assert.ok(Math.abs(got-want)<=tolerance,`${got} !== ${want}`);
const normal={x:{p1:{px:96,py:420,value:0},p2:{px:770,py:420,value:100}},y:{p1:{px:96,py:420,value:0},p2:{px:96,py:85,value:50}}};
near(core.mapImagePoint(normal,96,420).x,0);
near(core.mapImagePoint(normal,770,85).x,100);
near(core.mapImagePoint(normal,770,85).y,50);
near(core.mapImagePoint(normal,433,252.5).x,50);
near(core.mapImagePoint(normal,433,252.5).y,25);
near(core.mapImagePoint(normal,264.5,336.25).x,25);
near(core.mapImagePoint(normal,264.5,336.25).y,12.5);
const inverted={x:{p1:{px:770,py:420,value:0},p2:{px:96,py:420,value:100}},y:{p1:{px:96,py:85,value:0},p2:{px:96,py:420,value:50}}};
near(core.mapImagePoint(inverted,433,252.5).x,50);
near(core.mapImagePoint(inverted,433,252.5).y,25);
near(core.mapImagePoint(inverted,96,85).x,100);
near(core.mapImagePoint(inverted,96,85).y,0);
assert.throws(()=>core.linearAxis(20,0,20,50),/Degenerate/);
assert.throws(()=>core.linearAxis(0,1,20,1),/Degenerate/);
assert.throws(()=>core.linearAxis(0,NaN,20,1),/Non-finite/);
const points=[{id:'later',px:433,py:252.5},{id:'first',px:96,py:420},{id:'same-x',px:433,py:300}];
const order=core.orderedValues(points,normal);
assert.equal(order.map(p=>p.id).join(','),'first,later,same-x');
const encoded=new Uint8Array(await core.csvBytes(points,normal).arrayBuffer());
assert.deepEqual(Array.from(encoded.slice(0,3)),[0xef,0xbb,0xbf]);
const csv=new TextDecoder().decode(encoded).replace(/^\uFEFF/,'');
assert.equal(csv,'x,y\r\n0,0\r\n50,25\r\n50,17.91044776119403\r\n');
console.log('PASS T01: linear XY calibration at known pixel positions');
console.log('PASS T02: inverted X/Y axes and degenerate-axis validation');
console.log('PASS CSV: UTF-8 BOM, CRLF, sort X ascending, stable duplicate X');
